(function() {

	var AcaoSistema = {

		PESQUISAR_USUARIOS: 1,
		CADASTRAR_USUARIO: 2,
		REMOVER_USUARIO: 3,
		ATIVAR_DESATIVAR_USUARIO: 4,
		EDITAR_USUARIO: 5,
		VISUALIZAR_USUARIO: 6,
		PESQUISAR_MODULOS: 7,
		CADASTRAR_MODULO: 8,
		REMOVER_MODULO: 9,
		ATIVAR_DESATIVAR_MODULO: 10,
		EDITAR_MODULO: 11,
		VISUALIZAR_MODULO: 12,
		PESQUISAR_PERFIS: 13,
		CADASTRAR_PERFIL: 14,
		REMOVER_PERFIL: 15,
		EDITAR_PERFIL: 16,
		VISUALIZAR_PERFIL: 17,
		PESQUISAR_PERMISSOES: 18,
		CADASTRAR_PERMISSAO: 19,
		REMOVER_PERMISSAO: 20,
		EDITAR_PERMISSAO: 21,
		VISUALIZAR_PERMISSAO: 22,
		CRIAR_NOVAS_CREDENCIAIS: 23,
		CADASTRAR_SETOR: 24,
		PESQUISAR_SETOR: 25,
		EDITAR_SETOR: 26,
		VISUALIZAR_SETOR: 27,
		REMOVER_SETOR: 28,
		ATIVAR_DESATIVAR_SETOR: 29,
		CADASTRAR_PESSOA_FISICA: 101,
		LISTAR_PAISES: 102,
		LISTAR_ESTADOS: 103,
		LISTAR_MUNICIPIOS: 104,
		LISTAR_TIPOS_CONTATO: 105,
		FILTRAR_PESSOA_FISICA: 106,
		VISUALIZAR_PESSOA_FISICA: 107,
		EDITAR_PESSOA_FISICA: 108,
		REMOVER_PESSOA_FISICA: 109,
		CADASTRAR_PESSOA_JURIDICA: 110,
		LISTAR_PESSOAS_JURIDICAS: 111,
		VISUALIZAR_PESSOA_JURIDICA: 112,
		REMOVER_PESSOA_JURIDICA: 113,
		EDITAR_PESSOA_JURIDICA: 114,
		CADASTRAR_EMPREENDIMENTO: 115,
		LISTAR_EMPREENDIMENTOS: 116,
		VISUALIZAR_EMPREENDIMENTO: 117,
		REMOVER_EMPREENDIMENTO: 118,
		EDITAR_EMPREENDIMENTO: 119

	};

	exports.AcaoSistema = AcaoSistema;

})();
